language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - 'pypy'
  - 'pypy3'
matrix:
  allow_failures:
  - python: 'pypy3'
cache: pip
install:
  - pip install -e .[test]
script:
  - py.test run_tests.py
after_success:
  - py.test run_tests.py --cov flake8_builtins --cov-report term-missing
  - coveralls
